initlog is deprecated.  And, autofs is unused by any other part of the system. Also, it's not at all clear how sshd uses this package.  On our alpha boxes, removing pl_sshd left autofs without any deps, so I'm thinking the only reason it's there is because it  was 'Required' by the pl_sshd.spec

diff --git a/pl_sshd b/pl_sshd
--- a/pl_sshd
+++ b/pl_sshd
@@ -39,7 +39,8 @@ do_restart_sanity_check()
 start()
 {
 	echo -n $"Starting $prog:"
-	initlog -c "$SSHD $OPTIONS" && success || failure
+	#initlog -c "$SSHD $OPTIONS" && success || failure
+	$SSHD $OPTIONS && success || failure
 	RETVAL=$?
 	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/pl_sshd
 	echo
